### ISSUE TITLE
Feature Request: NuGet

### ISSUE THREAD

**Issue by kgiszewski** [leekelleher/umbraco-nested-content#1]
Would love to see this on NuGet for the usual reasons.  Well done fellas. #h5yr

**Comment by leekelleher** [comment]
:100: Thanks @kgiszewski

**Comment by jacobmohl** [comment]
+1 for that :-)

**Comment by YodasMyDad** [comment]
Any news on this?

**Comment by leekelleher** [comment]
@Jeavon has sent PR #9.  I need to review and merge in. (Same old excuse, not enough hours in a day!) 😵

**Comment by leekelleher** [comment]
I've finally wired up the NuGet and MyGet feeds with the AppVeyor CI build.

The NuGet package will be available on the next released (v0.1.2 - currently unscheduled), but the (bleeding-edge) package on the MyGet feed is available now: https://www.myget.org/F/umbraco-nested-content/
