### ISSUE TITLE
Multiple doc types can't be used when min and max is same value

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-nested-content#101]
When allowing multiple document types and min and max items is same value, e.g. 4 - then it init with 4 items of the document type, which is ordered first. But you have no option to switch one of the items to use one of the other allowed document types.

![image](https://cloud.githubusercontent.com/assets/2919859/22331188/5e197496-e3ca-11e6-9680-fe7a9003aef3.png)

**Comment by leekelleher** [comment]
This is definitely still a valid issue, but we didn't do anything with it before migrating the codebase over to Umbraco core (v7.7.0). So the best thing to do is to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
