### ISSUE TITLE
0.3.0 - Can't expand properties

### ISSUE THREAD

**Issue by 0Neji** [leekelleher/umbraco-nested-content#102]
Hi,

I've just run an upgrade for Nested Content going from 0.2.0 to 0.3.0 and I'm now unable to expand properties in the CMS. I can re-order them, add new items, and delete items but if I click either the title row or the edit button - nothing happens. In 0.2.0 the item expanded to show each property, I've tried reverting back to 0.2.0 and it works fine.

I'm on version 7.5.3 of Umbraco.

Any ideas?

Thanks,

Ben

**Comment by 0Neji** [comment]
For anyone else who may run into the same issues - looks like this might be a bug when using 7.5.3 - I didn't get any feedback from my console or network panel about errors etc so not sure about the issue. I did however upgrade Umbraco to 7.5.8 and everything now works as intended.

**Comment by leekelleher** [comment]
@0Neji Thanks for reporting it. Strange that 7.5.3 had an issue and 7.5.8 was fine.  We'll keep note of it, just in case anyone else raises similar. Thanks again!
