### ISSUE TITLE
Feature request: Option to disable item

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-nested-content#103]
It would be great to able to disable an item. We use Archetype on a existing project for some slides in a slideshow, where the editors often use the disable option, so they don't have to remove the item and add it later again, e.g. for some kind of season based content.

For Nested Content I can for now add a boolean property for this, but I think it would be better to have this as a core option. Maybe add a config option to enable or disable this.

**Comment by bjarnef** [comment]
Okay, I noticed there already is a PR for this feature: https://github.com/umco/umbraco-nested-content/pull/64

**Comment by leekelleher** [comment]
Thanks for the suggestion @bjarnef - we are undecided about whether to add the disable option.  At the time of PR #64, NestedContent was being put into the Umbraco core, so we didn't want to venture too far away from its simplicity.

Closing this ticket off, we can discuss further on PR #64.
