### ISSUE TITLE
Feature request: Option to use document type name in name template

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-nested-content#104]
I would be useful to be able to used name of document type in name template. E.g. instead of Item 1, Item 2, etc. then Slide 1, Slide 2, etc.

I have change the text directly in the config to "Slide", but is there a variable for the index/count?
For example, name template: `Slide {{count}}`

**Comment by mattbrailsford** [comment]
There should be a $index variable you can use.

**Comment by bjarnef** [comment]
I have tried something like `Slide {{$index}}`, but doesn't seem to work.
Is it only value af property editors that is replaced, when using it like `{{alias}}`?

**Comment by leekelleher** [comment]
@bjarnef It's a recent addition, (well, I say recently, it was in Oct 2016, 739070c1c02157212b875f3417b5b92e47eae7d8) ... but we haven't had a new release since. In the meantime, the [MyGet feed](https://www.myget.org/gallery/umbraco-packages) has the latest builds.

**Comment by bjarnef** [comment]
Ahh okay, I have currently v.0.3.0 installed :)

**Comment by leekelleher** [comment]
We're definitely overdue a new release... all I can say is that @mattbrailsford & I have been under heavy workloads for (at least) the past 6 months - and haven't prioritised getting a release out.
(_Same applies for our other packages - DTGE & Ditto are sorely overdue new releases too_)

I'll chat with @mattbrailsford about planning releases.

---

Closing this ticket off ❤️
