### ISSUE TITLE
Multinode picker "Add" button disappears at 2nd view

### ISSUE THREAD

**Issue by netaddicts** [leekelleher/umbraco-nested-content#107]
Ran into a strange issue that the add button is set to hidden when opening a nested content item for a 2nd time.

Path to repro:
Document type nc with single property of type "Multinode treepicker" (standard umbraco one)

![image](https://cloud.githubusercontent.com/assets/1563658/23361155/80b67966-fcef-11e6-827c-d4303df70d44.png)

Datatype nc

![image](https://cloud.githubusercontent.com/assets/1563658/23361180/a6e66f92-fcef-11e6-8452-b217c5045d45.png)

Add new property on document type, First view

![image](https://cloud.githubusercontent.com/assets/1563658/23361213/d26e9554-fcef-11e6-9d0b-52d3f0e2c26e.png)

And now switch between Item 1 and Item 2 (still fine now), back to Item 1 and this is the result

![image](https://cloud.githubusercontent.com/assets/1563658/23361228/e6df58fc-fcef-11e6-8509-7d1922fc2f15.png)

**Comment by mattbrailsford** [comment]
Is this the realise version? Or nightly?

**Comment by netaddicts** [comment]
Good point: umbraco v7.5.4, nc v0.3.0

**Comment by mattbrailsford** [comment]
I think it likely got fixed in commit d64692bc9aca21406c99e5dfde40f4783c79fa80 which I don't think is released yet. Might be worth giving the nightly a try and see if that works https://ci.appveyor.com/project/leekelleher/umbraco-nested-content/build/artifacts

**Comment by netaddicts** [comment]
Going to try it this afternoon.

--Dirk

**Comment by netaddicts** [comment]
I should have gone through the issues first, #70 says it's fixed, so closing this issue as it's duplicated

**Comment by mattbrailsford** [comment]
Thanks for the thorough bug report. I wish they all came like this :)

**Comment by netaddicts** [comment]
Yeah, been fighting exactly the same thing here in the office, constantly having to remind people to supply as much info as possible. Anyway, can confirm change made in commit https://github.com/umco/umbraco-nested-content/commit/d64692bc9aca21406c99e5dfde40f4783c79fa80 (took this file only for quick check) solves our problem.

Again, thanks for the great work, @mattbrailsford and @leekelleher  and any other collab on the project
