### ISSUE TITLE
Add Courier Resolver

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-nested-content#11]

**Comment by rustyswayne** [comment]
Hi Lee,

Is this the courier resolver for UaaS to assist in keeping the ContentType setting in the PreValue editor wired up when committing?

**Comment by leekelleher** [comment]
@rustyswayne Yes, it would cover adding all the associated DocType dependencies and resolving all the (nested) property values.

However I have not yet written any code for this yet. (We're not actually using NestedContent in production on UaaS yet)

Nik Wahlberg asked me about this too recently - @nwahlberg did you make any progress with developing one?

**Comment by rustyswayne** [comment]
@nwahlberg @leekelleher I have not written one of these yet, but have to figure them out (esp. for Merchello).  If you guys have a start and/or can point me to so info to get started I'd love to help on this one to get the idea.

**Comment by paulsterling** [comment]
Check out the Resolver for Archetype https://github.com/imulus/Archetype/tree/master/app/Umbraco/Archetype.Courier or Mortar https://github.com/leekelleher/umbraco-mortar/tree/develop/Src/Our.Umbraco.Mortar.Courier by way of getting a start.

**Comment by leekelleher** [comment]
Here are the links to the Courier resolvers that I wrote for Archetype and Mortar.

https://github.com/imulus/Archetype/blob/master/app/Umbraco/Archetype.Courier/DataResolvers/ArchetypeDataResolver.cs

https://github.com/leekelleher/umbraco-mortar/blob/develop/Src/Our.Umbraco.Mortar.Courier/DataResolvers/MortarDataResolver.cs

> Mortar is officially unreleased, but it's code has been used in both NestedContent and DocTypeGridEditor

There's some old Courier documentation on how to develop 3rd-party add ons, etc.
https://github.com/umbraco/Courier

---

Ah! Just noticed @paulsterling's reply (as I was typing this) :+1:

**Comment by nwahlberg** [comment]
He gents, this got de prioritized for us do we never did anything further. It will become relevant again in the next few weeks. 
We started working on it based on the archetype handler. 

> Sent from mobile (please pardon typos)

**Comment by leekelleher** [comment]
Awaiting feedback from https://github.com/kasperhhk/Umbraco.CourierProviders/issues/1

**Comment by paulsterling** [comment]
@leekelleher Posting here as the dis/play folks seem to have made some progress https://github.com/display/Umbraco-courier-providers

**Comment by YodasMyDad** [comment]
Is there anyway that the Nested Content provider above can be installed with Nested Content?

**Comment by leekelleher** [comment]
@YodasMyDad It'd need to be in a separate DLL/download, as the provider would need to depend on Courier assemblies, which if for regular Umbraco installs (that don't use Courier), it would throw a YSoD.

**Comment by YodasMyDad** [comment]
Ah ok. No problem.

**Comment by YodasMyDad** [comment]
Sorry bud. One last thing. Is it as simple as building that project above, and dumping the DLL in my bin folder to get it to work with UaaS?

**Comment by leekelleher** [comment]
Yes, just drop in the DLL.

Just to say that I still haven't tried out that resolver myself, so no idea
if it works or not. I keep asking for people to give me feedback... alas
pure radio silence :-(

**Comment by YodasMyDad** [comment]
Ok so I just tried those courier providers with standard Umbraco datatypes within my nested content and it worked fine. I added a limit of 4 in NestedContent so I could check if the prevalues went over correctly and they did along with the actual content :+1:

**Comment by leekelleher** [comment]
Thanks @YodasMyDad, that's great news!

**Comment by leekelleher** [comment]
Closing this one off, as a Courier resolver is available here:
https://github.com/display/Umbraco-courier-providers

...and going forwards, the move to Umbraco core should mean native support in Courier.
