### ISSUE TITLE
$dirty is not set when removing items

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-nested-content#113]
When removing items from Nested Content, it seems it doesn't set $dirty property on the form, which display "unsaved changes" prompt.
Tested with latest v.0.4.0 release.

Furthermore it could also set $dirty, when sorting of items is changed.
I did that in UrlPicker :)

When sorting change:
https://github.com/kgiszewski/uWestFest/blob/master/urlpicker/app/scripts/controllers/url.picker.controller.js#L294

When an item is removed:
https://github.com/kgiszewski/uWestFest/blob/master/urlpicker/app/scripts/controllers/url.picker.controller.js#L258

When an item is added:
https://github.com/kgiszewski/uWestFest/blob/master/urlpicker/app/scripts/controllers/url.picker.controller.js#L222

**Comment by leekelleher** [comment]
@bjarnef Thanks for the info. Sounds like it would be a great PR, if you want?

**Comment by bjarnef** [comment]
@leekelleher  I have submitted a PR for this https://github.com/umco/umbraco-nested-content/pull/114

**Comment by leekelleher** [comment]
Great, thanks @bjarnef!  I'll close this one off.
