### ISSUE TITLE
Renamed document types are not resolved

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-nested-content#117]
When renaming document type (incl. alias), the already selected document types in Nested Content config are not resolved.

Tested with Nested Content v.0.4.0 and Umbraco v7.5.11

E.g. below I have renamed the document type from "Nested Material" (nestedMaterial) to "Nested Element" (nestedElement).

![image](https://cloud.githubusercontent.com/assets/2919859/24454492/5ea44d62-148c-11e7-8806-df16b4352ee8.png)

I have to manually select the document type again.
![image](https://cloud.githubusercontent.com/assets/2919859/24454558/97cdea26-148c-11e7-976a-a0c0842b819d.png)

**Comment by leekelleher** [comment]
This is definitely still a valid issue, but we didn't do anything with it before migrating the codebase over to Umbraco core (v7.7.0). So the best thing to do is to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
