### ISSUE TITLE
Doc Types - Tab Drop Down List Not Saving When Setting Up New Data Type

### ISSUE THREAD

**Issue by jamiepittman** [leekelleher/umbraco-nested-content#119]
I installed this packaged on a new Umbraco v7.5.11 instance and discovered an issue when setting up a new nested content data type.

When selecting a Document type with multiple tabs, the tab drop down list populates. However, when I select anything other than the first tab and save it reloads and populates the drop down lists back to the first tab.

Checking the data on the content tree, only the properties from the first tab are visible on the data type. It appears to me that the doc type drop down list value is not saving but is rather staying as the default (first tab).

Before save:
![ss_beforesave](https://cloud.githubusercontent.com/assets/5632368/24660697/32b25c1c-191e-11e7-8206-2b40c8bbd73e.png)

After save:
![ss_aftersave](https://cloud.githubusercontent.com/assets/5632368/24660703/3824fa42-191e-11e7-8e06-155a88ae15d3.png)

**Comment by leekelleher** [comment]
This has been fixed in PR #131, (due for next release - _release date currently unknown_)
