### ISSUE TITLE
Featured Request : Deletion of Item Alert Message

### ISSUE THREAD

**Issue by suedeapple** [leekelleher/umbraco-nested-content#121]
The popup alert message current says

"Are you sure you want to delete this item?"

It would be nice, if this stated the "item name" as well,  

**"Are you sure you want to delete item: Slider Image? "**

**Comment by leekelleher** [comment]
Closing this request, as we don't want to introduce any features that are different to the version we migrated to (upcoming) Umbraco v7.7.0.

If you still want this feature in a future Umbraco release, please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
