### ISSUE TITLE
Cannot add a new content if multiple document types have been specified

### ISSUE THREAD

**Issue by netaddicts** [leekelleher/umbraco-nested-content#125]
Applies to v0.4

Repro path:

1. Create 2 new document types, each containing a single tab and single property (I had a ct with a textstring, other ct had a single content picker) > Default umbraco core stuff, nothing specific
2. Create new datatype and allow both document types
3. Add new property of this new datatype onto any existing or new document type 
4. Add new content and click the '+' button that should launch the "Choose dialog". Nothing happens.

Got a javascript error in Chrome dev tools

![image](https://cloud.githubusercontent.com/assets/1563658/25942716/d0559aec-363d-11e7-9527-a69fc7df3076.png)

**Comment by netaddicts** [comment]
Forgot to mention umb version which is 7.5.4 (Yes, we'll upgrade to 7.6+ at some point)

**Comment by leekelleher** [comment]
@netaddicts Hmmm, I haven't seen that JS error before 😞 
Just checking, the NC is added to a doctype on a regular page/node? It's not in a Vorto or DTGE, etc?

**Comment by netaddicts** [comment]
nope, was thinking that could be the deal breaker in our solution, hence reason for replicating first on a very basic setup,  and the page/node that holds the NC has this one and only property

**Comment by leekelleher** [comment]
We'll need to see if we can reproduce the error.  But I'm actively using NC (0.4) on Umbraco 7.5.13 (which has been upgraded through all the 7.5.x patches) and haven't seen this issue yet.

In the meantime, if you're happy to hack around with the CSS/JS? then there is PR #123 that attempts to remove the positioning calculation from the JS.
I've tweaked the CSS a little, [see my comment about that here](https://github.com/umco/umbraco-nested-content/pull/123#issuecomment-300441248).
If that works for you, then it's another +1 for that PR, and I'll try to get a new release out soon.

**Comment by netaddicts** [comment]
I'll give that PR a go and will provide feedback!
Already on the hacking path until something more official gets/was released

**Comment by netaddicts** [comment]
At least we've got it working again if we remove the "offending" js part as done in PR, so I guess it'll work as expected and some css sugar will most probably not interfere with the solution
Anyway, I'll redo on another install to verify things and provide more useful feedback

**Comment by leekelleher** [comment]
@netaddicts Ace, good to hear it's working now. 👍 

We'll still take a look at why the JS might have error'd.

**Comment by leekelleher** [comment]
I'm not sure of the status with this issue? I wasn't able to reproduce it.

Since we have migrated NC to (upcoming) Umbraco v7.7.0, we are not looking to make any changes to the codebase of the package version of NC.  If the issue persists, then please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
