### ISSUE TITLE
{{ pickerAlias | ncNodeName }} don't works with media picker

### ISSUE THREAD

**Issue by met67** [leekelleher/umbraco-nested-content#128]
I can't get {{ pickerAlias | ncNodeName }} to work as expected with a Media picker alias.

/M

**Comment by leekelleher** [comment]
@met67 - Thanks for raising this.  I haven't tested this with latest Umbraco, so not sure what's changed in terms of the Angular APIs... at a guess, and given that you've raised this, I suspect that the `entityResource` has new methods/parameters.

How are your JS dev skills? Would you be interesting helping us figure this out? I suspect it's around this line:
https://github.com/umco/umbraco-nested-content/blob/develop/src/Our.Umbraco.NestedContent/Web/UI/App_Plugins/NestedContent/Js/nestedcontent.filters.js#L37

Thanks!

**Comment by leekelleher** [comment]
@met67 Ah, just noticed the issue re-titled, and saw your replies on the forum.

>[Cross linking to forum post for reference](https://our.umbraco.org/projects/backoffice-extensions/nested-content/nested-content-feedback/85560-name-template-access-to-content-picker-properties#comment-272699).

I wasn't aware it was related to media nodes when I replied earlier. 😕 

@mattbrailsford - what are your thoughts about including an "ncMediaName" filter?
or are we creating a rod for our own back? (in terms of support and maintenance)

**Comment by dawoe** [comment]
Think the ncMediaName filter would be nice. As you can see from the forum post it is relatively easy to implement

**Comment by leekelleher** [comment]
@dawoe Yeah, it's pretty straight forward to add in 👍 
I'm thinking along the lines of adding a snippet to the docs for it, so people can extend if they want it.

**Comment by dawoe** [comment]
PR : https://github.com/umco/umbraco-nested-content/pull/129

**Comment by leekelleher** [comment]
Thanks @dawoe! I'll close this issue off, and discuss with @mattbrailsford on the PR itself. Cheers!
