### ISSUE TITLE
Multiple DocType Support

### ISSUE THREAD

**Issue by YodasMyDad** [leekelleher/umbraco-nested-content#13]
This isn't an issue, just an enhancement. I was thinking. like ArchType allows. You could choose multiple DocTypes within the Nested content. Then when you click the plus button it gives you the option to select which DocType to create (Inc showing the icon).

Then you could have a list of multiple different types....

**Comment by mattbrailsford** [comment]
In progress, see pull request #4. 

Closing this issue, but if you have any comments, please feel free to add them to the PR discussion thread.

**Comment by YodasMyDad** [comment]
Awesome :)
