### ISSUE TITLE
 Data type using nested content defaults to first tab in document type after save

### ISSUE THREAD

**Issue by apphutdev** [leekelleher/umbraco-nested-content#134]
![nested content datatype reverts to first tab](https://user-images.githubusercontent.com/22527712/27727589-04b7fb94-5d77-11e7-92e1-4ccc3b562b1a.gif)
**What did you do?**
Go to the developer section > Data Types> Create a new type using Nested Content. Add a document type with two or more tabs. I selected the second tab on the document type and clicked save.

**What did you expect to happen?**
The data type should remember the tab selection against the document type.

**What actually happened?**
The data type always reverts to the first tab on the document type in the tab dropdown list. Please see attached file.

I'm running Umbraco 7.6.3 with Nested Content 0.4.0

**Comment by leekelleher** [comment]
Closing this request, as we don't want to introduce any features that are different to the version we migrated to (upcoming) Umbraco v7.7.0.

If you still want this feature in a future Umbraco release, please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
