### ISSUE TITLE
Remove labels on nested property types

### ISSUE THREAD

**Issue by GiraffeCoding** [leekelleher/umbraco-nested-content#135]
Hi,

I've got an issue when nesting a nested content in side a nested content datatype. Both datatypes have labels as hidden but the properties in the nested content still show and are not required to be shown (highlighted in yellow):

![nested](https://user-images.githubusercontent.com/12425975/27837235-f790a602-60da-11e7-8194-eb02005b71e1.PNG)

Is there anyway around this?

Thanks in advance

**Comment by leekelleher** [comment]
Closing this request, as we don't want to introduce any features that are different to the version we migrated to (upcoming) Umbraco v7.7.0.

If you still want this feature in a future Umbraco release, please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
