### ISSUE TITLE
Nested Content on more than one Tab

### ISSUE THREAD

**Issue by lele7** [leekelleher/umbraco-nested-content#14]
HI!
I have created different nested data types with different doc types (Banner, Links, on so on...). On the home doc type I want to have each on a separated tab BUT the first one is working as expected and all the others have only an empty "Item 1"... any idea what I do wrong?

ps:
I used the vorto package for the multilingual stuff, but I think this shold not be a problem...

**Comment by leekelleher** [comment]
Hi @lele7, thanks for reporting this. (I'd also noticed your [forum post](https://our.umbraco.org/projects/backoffice-extensions/nested-content/nested-content-feedback/64707-Nested-Content-on-more-than-one-Tabs) too).

I've been on holiday, (hence no response), so have been slowly catching up on various issues, etc.

As far as I'm aware multiple instances of Nested Content on tabs should be fine.  I'll test this out over the next few days and let you know what I find out.

**Comment by mattbrailsford** [comment]
I've just tested this in Chrome/Firefox, 1 doctype with multiple instances of a nested content property, 1 reusing the same doctype, the other a different one, and all seemed to work fine with no side effects on each other.

What properties were on your doctypes? were you seeing any JS errors? How were you using it with vorto?

**Comment by lele7** [comment]
it seems to work now... maybe it was another issue with another package... sorry about that.

**Comment by mattbrailsford** [comment]
No worries, I'll close this issue for now, but if you do find the issue happens again, feel free to re-open it.
