### ISSUE TITLE
Nested content title formatting with properties

### ISSUE THREAD

**Issue by cmwalolo** [leekelleher/umbraco-nested-content#140]
We have some configurations in the nested content data types of our umbraco instances that are using some formatting as for example : (from {{dateRange.StartDate | date:"dd/MM/yyyy hh:mm"}} to {{dateRange.EndDate | date:"dd/MM/yyyy hh:mm"}})

It seems that this is not working any more since version 7.6.4 of Umbraco . We are using version 0.4.0 of the nested content

https://our.umbraco.org/forum/using-umbraco-and-getting-started/87906-nested-content-title-formatting

**Comment by cmwalolo** [comment]
I found an existing filter within umbraco that format the dates with moment as for example here 
{{time | momentDateTimeZone:"HH:mm"}} which is working better then the angular date filter.

**Comment by leekelleher** [comment]
@cmwalolo Cool, glad you found a solution.
It's a bit strange that the old filter stopped working in Umbraco 7.6.4 😕

**Comment by cmwalolo** [comment]
Apparently the angular date filter has a lot of issues. I don't think it was working well before, I just believed my colleague that it was working. I was creating a new filter, but had the good idea to first have a look in the umbraco source code what for filters were already existing  :)
