### ISSUE TITLE
Make obvious names for overview of the items inside the content

### ISSUE THREAD

**Issue by HeinPauwelyn** [leekelleher/umbraco-nested-content#143]
If you collapse the items of the nested content, you lost also the overview of the items inside it. See image below:

![image](https://user-images.githubusercontent.com/16222780/31849205-f7be6880-b63e-11e7-810a-e7eaefb1fe26.png)

Is it possible to change the name of `item x` to something obvious like `Monday` instead of `item 1`, `Tuesday` instead of `item 2` etc.

**Comment by leekelleher** [comment]
Hi @HeinPauwelyn,

You can use the Named Template to define the label however you like it. See the documentation for further details.

https://github.com/umco/umbraco-nested-content/blob/develop/docs/developers-guide.md#configuring-nested-content

**Comment by HeinPauwelyn** [comment]
Oke it's that what I needed

Thanks
