### ISSUE TITLE
Display lists of media types with content nodes.

### ISSUE THREAD

**Issue by JimBobSquarePants** [leekelleher/umbraco-nested-content#15]
See the discussion here:

https://our.umbraco.org/projects/backoffice-extensions/nested-content/nested-content-feedback/64582-Media-types

Ideally it would be great if we could pick from a list of media types to display in our content node. That way we can create simple objects that inherit from the built in media types Image etc for nested display.

**Comment by mattbrailsford** [comment]
Personally I don't think this should be implemented, when using Nested Content, Doc types shouldn't be considered as "document types" but more "data blue prints". In this sense I don't see the point in splitting them up. Yes, I see it would give you inheritance on the current existing media nodes, but I'm not sure if it would just be more confusing having definitions in multiple places (again, this makes sense for media and content nodes, but for NC, I'm not sure it does). In this situation I would probably just make a base NC doc type to inherit from which has the same properies. Yes, it's duplicating what's in the media section, but it gives you the flexibility to grow in different directions.

Maybe this is more an argument for having nested content blueprints completely separated from doc types / media types to prevent any connotations of it being one or the other, however I don't think this would be possible without core code changes.

**Comment by JimBobSquarePants** [comment]
Fair do's, I just stuck the class in a folder in my solution called. `IDontBelongHere` and moved on. :smile: 

Really impressed with what I've seen of the package. Great stuff!
