### ISSUE TITLE
Tab Alias Case-Sensitive?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-nested-content#25]
It seems that if the tab-alias (entered in the DataType prevalues) is a different casing to the actual DocType's tab alias, then the DocType properties wont be loaded on the editor.

@bkclerke hit the issue when upgrading from v0.1.1 to v0.2.0 ...
https://our.umbraco.org/forum/umbraco-7/using-umbraco-7//68066-upgrading-nested-content-package-and-items-disappear-in-umbraco-content-tree

@mattbrailsford Is the tab-alias check done in the JS? I found it in 2 places: controller and directives.

**Comment by leekelleher** [comment]
@mattbrailsford From looking at the v0.1.1 source, I can only find 1 place where the tab-alias is checked...

https://github.com/leekelleher/umbraco-nested-content/blob/0.1.1/Src/Our.Umbraco.NestedContent/Web/UI/App_Plugins/NestedContent/Js/nestedcontent.directives.js#L12

But as far as I can tell, JS will do a case-sensitive comparison.  I'm a bit confused.

**Comment by kjac** [comment]
Sounds weird. I'll have to have a look at it in the weekend, kid permitting.

**Comment by bkclerke** [comment]
If there is anything I can provide / do to help check this out please let me know! I did check my backup just to make sure, I had 'content' prior to the upgrade and it worked. I feel like maybe I was just cached of some sort. :)

**Comment by kjac** [comment]
Hey @bkclerke :) The issue was very real indeed, and I believe @mattbrailsford has fixed it for the next release.

**Comment by leekelleher** [comment]
Thanks @bkclerke @kjac! Yeah, @mattbrailsford added a fix for this in commit 33810d56c771e8b2dbb80c79acc071f95ec581c2

I'll close this ticket now.
