### ISSUE TITLE
Validation of Nested Content in Nested Content

### ISSUE THREAD

**Issue by sandervdpas** [leekelleher/umbraco-nested-content#26]
Hello Lee,

I'm using Nested Content in Nested Content wich works awful! The only problem is the validation doesn't work in the Nested Content I use in another Nested Content.

I've got a property on a content doctype from datatype Nested Content (file nested_content_blocks.png and Nested_blocks_datatype.png) as blocks.

One of the blocks uses another Nested Content inside that item (nested_blocks_doctype_property.png) where the title, intro and url are checked as mandatory in the doctype (Nested_Content_mandatory_fields.png) but I can save it without any mandatory errors.

The main Nested Content validation works fine (Main_nested_content_validation.png), but the validation of the Nested Content in Nested Content wouldn't be shown (validation_of_nested_Content_in_nested_content).

Hopefully it's a little bit clear for you?
Do you have any idea why this won't work?

I've added some screenshots for explanation.

![nested_content_overview_image_item](https://cloud.githubusercontent.com/assets/9931405/9135100/69330a80-3d0a-11e5-82af-bad0a01b7b00.png)
![nested_content_overview_image_datatype](https://cloud.githubusercontent.com/assets/9931405/9135104/6935de18-3d0a-11e5-8310-4c2563c4158b.png)
![nested_blocks_datatype](https://cloud.githubusercontent.com/assets/9931405/9135102/693341c6-3d0a-11e5-9a84-8e8dc09d1eae.png)
![nested_content_in_nested_content_item](https://cloud.githubusercontent.com/assets/9931405/9135103/6934fa0c-3d0a-11e5-911f-5673bb9a5ab0.png)
![nested_content_in_nested_content](https://cloud.githubusercontent.com/assets/9931405/9135101/6933169c-3d0a-11e5-8a9e-2989bc57046c.png)
![nested_blocks_doctype_property](https://cloud.githubusercontent.com/assets/9931405/9135099/6932be7c-3d0a-11e5-9075-8c420d867dc3.png)
![nested_content_blocks](https://cloud.githubusercontent.com/assets/9931405/9135105/6942ddac-3d0a-11e5-841b-82f82999d268.png)
![nested_content_mandatory_fields](https://cloud.githubusercontent.com/assets/9931405/9135255/d0824cfe-3d0b-11e5-9c88-e490f455f41e.png)
![main_nested_content_validation](https://cloud.githubusercontent.com/assets/9931405/9135346/99d87c18-3d0c-11e5-8717-666fd80afd14.png)
![validation_of_nested_content_in_nested_content](https://cloud.githubusercontent.com/assets/9931405/9135368/ca289eca-3d0c-11e5-82e5-061e367143bb.png)

**Comment by mattbrailsford** [comment]
Hey @sandervdpas 

Thanks for the thorough report, it's really great to get issue reports as complete as this :)

Currently in NC we handle the validation via a custom validation control that runs on the server as this is the only way we could get it to work how we would like, this does unfortunately mean that we can only validate the first level of fields. 

Whilst this is a restriction of our validator logic, it is a restriction we are happy with as we are also taking an active decision to keep NC simple and focused on its primary goal which is predominantly to manage simple lists of data. We know people will attempt to use NC within NC, but that isn't something we are actively encouraging as at that point it is becoming a general purpose property editor for managing complex data structures which is not what NC is for.

From looking at your screenshots, It would seem you are using NC to manage many types of content which in that case I would likely suggest you look at alternative approaches such as the Grid, or using content blocks and a widget picker or maybe a custom solution specific to your needs.

Apologies if this isn't the reply you were hoping for, but sometimes running a project involves saying no and sticking with the principles of the what it was intended for.
