### ISSUE TITLE
Awesome package but we miss the image cropper

### ISSUE THREAD

**Issue by fergers** [leekelleher/umbraco-nested-content#27]
hello

First of all I wanna thank you for making this awesome package! At the moment iI am developing a lot of website in umbraco which consist of blocks. Your nested content plugin comes in very handy because the blocks can now be added/edited on the page itself instead of in Media or a child content page.

I know there is currently no support for the image cropper functionality but I think this will be a great functionality! Unfortunately because of my lack of Angular knowledge I can't try to add it myself.
Now my question is: Is there a chance this functionality will//can be added on the short term? 

I hope you guys can answer my question!

**Comment by mattbrailsford** [comment]
Unfortunately, no :)

The way the images cropper / upload fields work, they use code behind to find a single upload file associated with a single prop editor on the "real" node being edited. By using NC though you are in effect making many upload fields associated with a property editor (NC being the property editor on the node) so when you save, the upload field code behind has no way of knowing which file is associated with it.

The best option we have right now is to suggest you use the media picker which has an upload feature within the dialog. Unfortunately that doesn't support the image cropper though so you would have to go into the media section to set the crop.

**Comment by fergers** [comment]
Thanks for the quick answer! In that case we will find a way to work around
this!

2015-08-11 17:23 GMT+02:00 Matt Brailsford notifications@github.com:
