### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by jbreuer** [leekelleher/umbraco-nested-content#29]
If a new row is added to Nested Content it would be nice if an event is fired so we can modify it. For example set the current date on a date field. More info in this Twitter conversation: https://twitter.com/j_breuer/status/636470103610138624

An event after a row is removed is probably also nice.

**Comment by jbreuer** [comment]
As a workaround you could hook into the WebApiHandler event: https://github.com/jbreuer/Hybrid-Framework-for-Umbraco-v7-Best-Practises/blob/master/Umbraco.Extensions/Utilities/WebApiHandler.cs#L19

That event get's called each time a new row is added to nested content. In the example it's used to set the start node of the media picker, but you can also use it to override content. For example the date.

**Comment by leekelleher** [comment]
Closing this request, as we don't want to introduce any features that are different to the version we migrated to (upcoming) Umbraco v7.7.0.

If you still want this feature in a future Umbraco release, please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
