### ISSUE TITLE
Support multiple doctypes

### ISSUE THREAD

**Issue by kjac** [leekelleher/umbraco-nested-content#3]
Heya, 

Lovely package. Would you consider having it support multiple doctypes? I have a working implementation of multiple doctypes that I can push as a PR if you want it.

Regards,
Kenn

**Comment by mattbrailsford** [comment]
What's the use case?

**Comment by kjac** [comment]
Wanting different list item types in the same list? Instead of having one mother-of-all-list-items doctype to handle all permutations of whatever I want my editors to be able to enter, I could create multiple smaller doctypes tailored specifically to different uses, and fragment my frontend rendering accordingly.

**Comment by mattbrailsford** [comment]
Hmm, possibly. Could use a similar dialog as the grid when choosing a grid
item type to pick one.

How are you doing it in your PR?

**Comment by kjac** [comment]
Precisely like the grid. Same dialog just using the allowed doctype icons
and names.
I'll submit it tomorrow evening, then you can have a look.

**Comment by leekelleher** [comment]
Wondering how assigning multiple DocType and tab combinations UI would work?

**Comment by kgiszewski** [comment]
+1

**Comment by kjac** [comment]
For the time being I'm simply assuming that the different selected doctypes will all use the same tab name, but it shouldn't be too much trouble to create a new property editor that allows for pairing doctypes and tab names for the datatype configuration.

**Comment by AussieInSeattle** [comment]
+1

**Comment by leekelleher** [comment]
Closing this ticket, as we can continue discussions on PR #4.
