### ISSUE TITLE
Localized titles for icon anchors

### ISSUE THREAD

**Issue by rustyswayne** [leekelleher/umbraco-nested-content#30]
Hey guys,  Not sure if you want this, but in Merchello I've now "borrowed" your icon styles in an attempts to keep unified with the back office and with some of the great property editors (like NC) out there.  

In Merchello, I needed to add a few more that were not as obvious as edit, move and delete so I added localized titles to the anchor surrounding the icon (i).  I've updated my fork of Nested Content to include these for you to evaluate and decide whether or not you think it's a good idea.  

Will submit a pull shortly.

**Comment by leekelleher** [comment]
Thanks @rustyswayne - sounds good, we'll review it!  Closing this issue, we can chat on the PR #31
