### ISSUE TITLE
Argument reference per scaffold Item

### ISSUE THREAD

**Issue by edejesus87** [leekelleher/umbraco-nested-content#32]
Hi, 
I have added a custom property on a document type and i need to load certain type of datas based on document type how can i achieve this on my custom property? its just a simple dropdown, i want to know what kind doctype alias and pass it to my web api Thanks

**Comment by leekelleher** [comment]
Hi @edejesus87,

This sounds more of an implementation concern, rather than a bug with Nested Content.

Could you post a topic on the Our Umbraco forum please?
https://our.umbraco.org/projects/backoffice-extensions/nested-content/nested-content-feedback/

Thanks,
Lee.
