### ISSUE TITLE
Back Office Hangs After Install Umbraco 7.2.8

### ISSUE THREAD

**Issue by DanielGillett** [leekelleher/umbraco-nested-content#35]
Hello,

Your package looks to be just what I need!  

However, with a fresh install of Umbraco 7.2.8 (tried with built-in package installer and also with Nuget).

After the install, umbraco back office hangs.  I can still navigate the website, but I cannot log into the back office.  I think this is something in one of the Angular files that's causing the problem.  The back office works again when I delete the NestedContent folder from the App_Plugins folder.

I've noticed...
the "nestedcontent.services.js" file is empty
in the "nestedcontent.resources.js" file specifies a url "/umbraco/backoffice/NestedContent/NestedContentApi/GetContentTypes" which does not exist. I've checked the file structure of umbraco and there is no "/umbraco/backoffice/" directory.

I'm running VS 2013 Web and have installed Umbraco through Nuget.

Sorry if this doesn't help.  Please tell me what to check.  Happy to help!

Kind regards,
Daniel

**Comment by DanielGillett** [comment]
Um... Hello?
Is no one else having this issue installing NC with U7.2.8?
help.  ;-(

**Comment by leekelleher** [comment]
Hi @DanielGillett,

Not sure what to say, I haven't experienced this myself.

The "nestedcontent.services.js" file is intentionally empty, (for future use).

The "/umbraco/backoffice/" directory in the resources URL is a virtual one, it is reserved for Web API requests, doesn't exist on disk.

The only thing I can think of is that the NuGet install wasn't successful, could you check if the "Our.Umbraco.NestedContent.dll" is in the "/bin" folder?

---

It might be better posting on the Our Umbraco forum, as other community members might have experienced a similar situation?
https://our.umbraco.org/projects/backoffice-extensions/nested-content/nested-content-feedback/

(The issue tracker on this GitHub repo is intended for specific bug reporting and feature requests)

Thanks, Lee

**Comment by mattbrailsford** [comment]
Not had any further feedback so closing issue

**Comment by ibraheemhlaiyil** [comment]
Having the same issue.

Umbraco 7.4.2, .NET 4.6
NestedContent 0.2
VS2015

Front end loads but backoffice doesn't. I also had it where the front end also did not load.

Initially installed via backoffice, then nuget via VS2015. Uninstalled/re-installed via nuget several times until the front end loads now but still not the backoffice.

**Comment by leekelleher** [comment]
@ibraheemhlaiyil When you say it doesn't load, do you mean a blank screen, or a YSoD error?

Are you able to check your web-browser's dev tools for any JavaScript errors?

Do you have any other packages installed?

**Comment by ibraheemhlaiyil** [comment]
Blank screen, page content (HTML) is downloaded but nothing displays.

Just tested it in Chrome and it seems fine, testing in IE11 produces the error.

Looking in the IE11 dev console I see the following error which does not show in Chrome:

```
HTML1514: Extra "<body>" tag found. Only one "<body>" tag should exist per document.
File: umbraco, Line: 22, Column: 1
```

**Comment by ibraheemhlaiyil** [comment]
No other packages installed.

**Comment by leekelleher** [comment]
@ibraheemhlaiyil Sorry, in terms of fixing an actual bug, there isn't much for me to go on here.

It seems strange that it would work in one browser but not another. Along with that no one else has raised this issue with us about Umbraco v7.4.2.

My advise is to post on the Our Umbraco forum, as other community members might have experienced a similar situation?
https://our.umbraco.org/projects/backoffice-extensions/nested-content/nested-content-feedback/

If you are able to pin-point a specific bug, I'm totally happy to look into it further.

**Comment by ibraheemhlaiyil** [comment]
Thanks @leekelleher I'll download the source package and see if I can work out where the problem lies.
