### ISSUE TITLE
Dropdown List Property in nameTemplate resolves to ID, not to value

### ISSUE THREAD

**Issue by LeoSchleicher** [leekelleher/umbraco-nested-content#42]
When I try to use dropdown list as nameTemplate it shows Prevalue ID instead of property value

**Comment by mattbrailsford** [comment]
That's just how it works I'm afraid, as the nameTemplate only runs on the SAVED value, which a dropdown saves the prevalues ID, not it's value.

**Comment by leekelleher** [comment]
Closing issue, it's beyond the current scope of NC.

**Comment by kunal999** [comment]
Since Nested content is now built-into Umbraco 7.7, is this the right repo to +1 this request?

**Comment by ocastele** [comment]
I have the same problem, any progress on this? Would be very helpfull.

**Comment by leekelleher** [comment]
Hi @kunal999 and @ocastele - this repository is no longer the best place to raise issues about Nested Content, please use the Umbraco issue tracker: <http://issues.umbraco.org/issues/U4?q=Nested%20Content#newissue=yes>
Thanks 🙂
