### ISSUE TITLE
Add some preventative measures to prevent breakages

### ISSUE THREAD

**Issue by mattbrailsford** [leekelleher/umbraco-nested-content#43]
Initially NC was built to store a doc types guid, which was as a means to prevent breakages should someone decide to rename a doc types alias. With the recent change to storing the alias instead, it's now a bit more prone to breakages.

Given we have made sure to prefix the fields that hold the doc type / tab aliases, I wonder if we shouldn't try and add some preventative measures to try and fix things as changes are made, ie, if someone changes the name of a doc type, do a quick search and replace in the database for "ncContentTypeAlias: 'OldAliasName'" and fix the changed entry doing something similar with the tab alias. 

This could be done quite easily in the database, but I guess we also need to consider updating the lucene index, as well as the xml content cache.

There is also the question of how far we go, ie, do we also try and detect property alias changes as well?

**Comment by leekelleher** [comment]
Closing this request, any future features can be raised for the Umbraco core version of NC.
