### ISSUE TITLE
Image Cropper inside Nested Content: impossible to save

### ISSUE THREAD

**Issue by LeoSchleicher** [leekelleher/umbraco-nested-content#44]
Hi!
In UI Image Cropper works as it should, but selected value not saved after publishing

**Comment by mattbrailsford** [comment]
HI Leo,

At the moment neither the image uploader / image cropper work inside Nested Content. The only workaround currently is to just use a media picker and manage the crops from the media section.

We are working on adding this support, but it won't be for a while.

Matt
