### ISSUE TITLE
Support returning dynamic properties like DynamicPublishedContent

### ISSUE THREAD

**Issue by Korayem** [leekelleher/umbraco-nested-content#45]
I love Umbraco's support of Dynamic because it simplifies readability of code from this:

```
@foreach (var class in Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("classes"))
    {
        <li>@class.name @class.code @class.location</li>
    }
```

to this

```
    @foreach (var class in CurrentPage.classes)
    {
        <li>@class.name @class.code @class.location</li>
    }
```

**Comment by leekelleher** [comment]
Hey @Korayem, thanks for the suggestion.  To be truthful, my initial reaction was "nah", but in true Umbraco spirit I've had a look to see if it's possible to make it NC's object value to be dynamic.

From digging into the Umbraco core source-code, I'd half-expected the `DynamicPublishedContent` object to cast any `IPublishedContent` property-values to also be dynamic.  Unfortunately it doesn't, it returns the property-value directly from the associated PropertyValueConverter.

Meaning in the case of NC, when you call `@CurrentPage.directions` the object-type would be `IEnumerable<IPublishedContent>`. (So there's no extra dynamic magic going on behind the scenes there)

The workaround solutions to make NC work with `DynamicPublishedContent` are...
1. Un-register the built-in `NestedContentValueConverter`; replacing it with one that returns either a `DynamicPublishedContent` or `DynamicPublishedContentList`.
2. We refactor `NestedContentValueConverter` to support `DynamicPublishedContent`. See how @Jeavon's Core Property Value Converters project handles this... a helper method for [`DynamicInvocation()`](https://github.com/Jeavon/Umbraco-Core-Property-Value-Converters/blob/v3/Our.Umbraco.PropertyConverters/Utilities/ConverterHelper.cs#L42), with example [usage for the MNTP converter](https://github.com/Jeavon/Umbraco-Core-Property-Value-Converters/blob/v3/Our.Umbraco.PropertyConverters/MultiNodeTreePickerPropertyConverter.cs#L109).

---

Personally I'm not a fan of the dynamics approach, but I'm totally happy for the discussion. // @mattbrailsford

**Comment by Korayem** [comment]
Thanks @leekelleher. Your reply was an eye opener on where to look for.

For our case, we achieved desired outcome to fix NC's lack of dynamic support by casting the dynamic property to  `IEnumerable<IPublishedContent>` then projecting result into a new `DynamicPublishedContent` object achieving desired result:

```
@foreach(dynamic class in ((IEnumerable<IPublishedContent>)CurrentPage.classes).Select(i=>new DynamicPublishedContent(i)))
    {
        <li>@class.name @class.code @class.location</li>
     }
```

It works but isn't as beautiful as magically referencing everything dynamically.

**Comment by jamiepollock** [comment]
I have to say I'm also with @leekelleher on this. I personally use view model classes versus Dynamics to keep my views readable. I appreciate this isn't an option or the accepted dev solution for others. Dynamics have their place. :)

I'm all for the idea, so long as it doesn't prevent or complicate the development of new features for the package.

Sorry I can't be any more useful than this.

**Comment by dawoe** [comment]
As I think the core has plans for moving away from dynamics I would say don't support it. 
Niels comment on this article makes me believe the core will drop the support for dynamics at some point : http://24days.in/umbraco/2015/strongly-typed-vs-dynamic-content-access/

Dave

**Comment by mattbrailsford** [comment]
Given the recent shift to models builder in 7.4 and it being on by default, I would say it looks like dynamics is not longer the preferred "introductory" method of getting started with Umbraco, so I'm gonna say unless anyone wants to submit a PR for it, we won't be adding it ourselves.
