### ISSUE TITLE
Move, then modify RTE saves in wrong item

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-nested-content#46]
@mattbrailsford An issue was raised on the forum - [Rich Text Editor (TinyMce) in NestedContent](https://our.umbraco.org/projects/backoffice-extensions/nested-content/nested-content-feedback/74019-rich-text-editor-tinymce-in-nestedcontent).

I am able to reproduce the bug, which only happens in a specific scenario.

**Steps to reproduce**
1. Make a simple NC list with a single DocType (that contains an RTE property)
2. Make 3 items/rows, (called A, B and C)
3. Add some dummy content, save the node (property-value)
4. Reload the content page
5. Move the first item (A) to the bottom of the list, then...
   1. Expand item A
   2. Modify the RTE value
   3. Save the node (property-value)
6. Reload the content page
7. Notice that...
   1. Item A's RTE value has been reverted
   2. Item C contains the modified RTE value (from item A)

---

The key part seems to be when the RTE is modified after the item has been moved.  If I modified the RTE value, then move it, all the items persist correctly.

Any ideas?

**Comment by kgiszewski** [comment]
Just in case it matters (though I think you've been the loop), this was a problem area for us too. @kjac ended up tweaking ours though we had slightly different symptoms: https://github.com/imulus/Archetype/blob/master/app/controllers/controller.js#L47-L72

**Comment by leekelleher** [comment]
Potential fix for this in PR #55

**Comment by AliSheikhTaheri** [comment]
Hi Lee 

We have been having the same issue with the latest version of Nested Content (0.2.0).

It also happens if you just reorder the content with two RTEs and without modifying the value. 

so the fix https://github.com/leekelleher/umbraco-nested-content/commit/61804487b2c27dbf6d7863d79f1540da14d1ce11 here changing the `ng-show` to `ng-if` seems to fixed the issue. 

Do you have any idea when this fix would be in the next version of NC?

Thanks
Ali

**Comment by leekelleher** [comment]
Hi @AliSheikhTaheri, currently we have no timescales for the next release (v0.3.0), but the latest bleeding-edge version is available via MyGet:

https://www.myget.org/feed/umbraco-packages/package/nuget/Our.Umbraco.NestedContent

**Comment by AliSheikhTaheri** [comment]
Hi Lee, Thanks for your reply. I have amended that view manually for now and we will wait for the release on NuGet as we are using this awesome package on a live site :+1:

**Comment by leekelleher** [comment]
Closing this issue, as commit 61804487b2c27dbf6d7863d79f1540da14d1ce11 has resolved it.
