### ISSUE TITLE
Umbraco 7.4 layout issues.

### ISSUE THREAD

**Issue by pgregorynz** [leekelleher/umbraco-nested-content#48]
Hey guys.  The editor works in Umbraco 7.4 however there have been some updates to the layout of the back office.  When you have Nested content inside nested content it renders the add content button incorrectly. ;)

**Comment by leekelleher** [comment]
@pgregorynz Thanks for the heads up!

I'll pass this on to @mattbrailsford ... he'd mentioned about revising the UI to match 7.4's Grid style updates.

**Comment by jbreuer** [comment]
Just upgrade a big website to Umbraco 7.4-beta2 to do some testing. Somehow the RTE doesn't show the label anymore and if there is a label the alignment could still be wrong. See attachments to see the difference between Umbraco 7.4 and 7.3. 

If the layout needs to be updated maybe the space between the label and the property could also be smaller. There is a lot of empty room in the 7.3 version.

![74](https://cloud.githubusercontent.com/assets/5444597/12703236/8fca6944-c83e-11e5-9d21-46559410cb53.png)
![73](https://cloud.githubusercontent.com/assets/5444597/12703237/93b9d4b8-c83e-11e5-9f8f-c79c43b02481.png)

**Comment by jbreuer** [comment]
Upgraded to 7.4 RC and it looks the same. I know you guys are busy, but do you have any idea when this will be fixed?

**Comment by mattbrailsford** [comment]
Sorry bud, just a bit busy with client work. Happy to accept a PR if you have the time?
