### ISSUE TITLE
PropertyValueConverter and Umbraco 7.4 ModelsBuilder

### ISSUE THREAD

**Issue by cwjackso** [leekelleher/umbraco-nested-content#49]
Just starting a new project on Umbraco 7.4 and using the now built in ModelsBuilder. It seems to interact nicely with property value converters in most cases (some of my own and the Core Property Value Converters module) but after adding in a Nested content property the model builder only typed the property as "object" rather than expected "IEnumerable<IPublishedContent>"

Not a show stopper but would be great if they worked together to build a strong typed model.

Thanks

**Comment by leekelleher** [comment]
@cwjackso Thanks for raising this.  Any ideas how to make it work?

I haven't used ModelBuilder (with Nested Content) before, and haven't had any time to check out Umbraco 7.4 yet.

**Comment by leekelleher** [comment]
At a guess, I think the [`NestedContentValueConverter`](https://github.com/leekelleher/umbraco-nested-content/blob/develop/src/Our.Umbraco.NestedContent/Converters/NestedContentValueConverter.cs) might need to be decorated with a `PropertyValueType` attribute...

``` csharp
[PropertyValueType(typeof(IEnumerable<IPublishedContent>))]
```

**Comment by cwjackso** [comment]
Sounds like its worth a go. Do you want me test it and add a pull request?

**Comment by leekelleher** [comment]
@cwjackso If you could, that would be fantastic!

(Takes the pressure off me - and client deadlines :sweat_smile:)

**Comment by cwjackso** [comment]
See what I can do tonight after work - I'm on my own client deadline too  :)

**Comment by cwjackso** [comment]
Works as expected.

Thanks

**Comment by leekelleher** [comment]
Cool, thanks @cwjackso, it's very much appreciated! #h5yr

Closing this issue off, we can continue any discussion about the PR itself on #51
