### ISSUE TITLE
Map data when upgrading package to v. 0.2.0

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-nested-content#52]
I upgraded a site from Umbraco 7.2.4 to 7.4.1 ... afterwards I upgraded Nested Content package from v. 0.1.1 to v. 0.2.0, but due new changes to support multiple doc types, Nested Content doesn't map the data for the existing content and therefore no items in the editor, although umbraco.config has the old json.

Is it possible to map the old values for doc type, tab and name template for the new multi-items config?

At the moment I have to manually select the doc type in dropdown, an enter the values for tab and name template.

**Comment by leekelleher** [comment]
Closing this one off, as there is code that should upgrade the prevalue data from v0.1.x to v0.2.0 format. (See [L77 in `NestedContentHelper`](https://github.com/leekelleher/umbraco-nested-content/blob/develop/src/Our.Umbraco.NestedContent/Helpers/NestedContentHelper.cs#L77).)

Apologies for the long delay in responding to this.
