### ISSUE TITLE
Not unique id's for input fields

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-nested-content#54]
It seems that the id's of the input fields not are unique enough.

E.g. I have a textbox with alias `transportName`, therefore it use `id="transportName"` and `for="transportName"` on the label.

But because it is used for each item in the list, it will only focus on the first "transport name" input. Furthermore it might be an issue if there actually was added a property to the node with alias `transportName`.

So make it more unique, e.g. something like:

`nested-{{alias}}-{{$index}}`

**Comment by mattbrailsford** [comment]
I'm pretty sure this is outside our control as we don't control the rendering of the input fields, we just offload it to the relevant property editors view so this is ultimately something that would have to be done in the wrapped PE (I think it would be a bad idea for NC to attempt to modify this within our own logic as it could have adverse effect if someone relies on the format of an ID in their PE)

**Comment by bjarnef** [comment]
Yes, you are right Matt.
There was a similar issue with Archetype, but they use its own directive..  
I took a look at the source code and see Nested Content use umb-property and umb-editor directives.. 

So it should probably be fixed here and some other places.. 
https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html

I am not sure if there is something to check each level like with nedsted ng-repeat,  where e.g.child can access parent index.

**Comment by leekelleher** [comment]
Closing this off, as it's beyond the control of Nested Content.

This is something that should be raised with Umbraco core team for consideration.
