### ISSUE TITLE
Min and max for the doctypes

### ISSUE THREAD

**Issue by sebastiandammark** [leekelleher/umbraco-nested-content#56]
Would it be possible to add min and max on the doctypes, so that a specific doctype cannot be created more than once.

In the attached screendump Shortcuts must and can only be applied once.
And Section must be applied once and can only be applied 3 times.

![screen shot 2016-03-16 at 15 35 39](https://cloud.githubusercontent.com/assets/1575483/13816178/a45c245c-eb8d-11e5-9dd0-fa7c50f9568f.png)

**Comment by mattbrailsford** [comment]
Personally I don't think the min field is relevant, as it would be tricky to enforce that X many MUST exist. Maximum possibly, but I really don't like the prevalue editor for each doctype getting so wide so if anyone fancies looking at this then I suggest we look at alternative UI for administering the doctype settings.

**Comment by leekelleher** [comment]
Closing this one off, as we wouldn't implement this feature ourselves in the standalone version of the package.

It could be suggested for the upcoming native Umbraco version, but that said, there's nothing in native Umbraco that limits the number of times a doctype can be used in the content tree.

It's definitely an interesting idea, worth more discussion (on the Umbraco issue tracker).
