### ISSUE TITLE
Programatically add values to Nested Content

### ISSUE THREAD

**Issue by harvzor** [leekelleher/umbraco-nested-content#57]
Is there some way to programmatically add values to a Nested Content property type on a node?

I believe I am supposed to save JSON to the `VALUE` variable, but I'm not sure out to do this:

```
var test = ContentService.CreateContent("Test", parentId, "testAlias");

test.SetValue("nestedContentProperty", VALUE);

ContentService.SaveAndPublishWithStatus(test);
```

Is there some namespace that I can access the `DetachedPublishedContent` from? Maybe I could use that model to create the data. Thanks for any help.

**Comment by leekelleher** [comment]
@HarveyWilliams Yes, your correct with that the `VALUE` needs to be in JSON format.

The format is like this:

``` json
{
    "name" : "Some item name",
    "ncContentTypeAlias" : "yourDocTypeAlias",
    "propertyAlias1" : "some value 1",
    "propertyAlias2" : "some value 2"
}
```

The format of the individual property-values will need to be in the correct format of the corresponding property-editor, e.g. if you've nested another NC, then that will need to be a JSON object, rather than a JSON-encoded string.

As for using `DetachedPublishedContent` to populate it wouldn't work, as for internal use to create the read-only `IPublishedContent` for front-end rendering.

I hope this helps?

**Comment by harvzor** [comment]
@leekelleher Nice that worked! It seems that it accepts arrays too. I'm not a fan of generating strings of JSON, but I still needed a dynamic approach to adding properties to my JSON object. I opted for an expando object:

```
var test = ContentService.CreateContent("Test", parentId, "testAlias");

var ncItems = new List<dynamic>();

foreach (DateTime date in dates)
{
    dynamic ncItem = new ExpandoObject();

    ((IDictionary<string, object>)ncItem).Add("name", "Some item name");
    ((IDictionary<string, object>)ncItem).Add("ncContentTypeAlias", "ncItemAlias");
    ((IDictionary<string, object>)ncItem).Add("date", date);

    ncItems.Add(ncItem);
}

var ncItemString= Newtonsoft.Json.JsonConvert.SerializeObject(ncItems);

test.SetValue("nestedContentProperty", ncItemString);

ContentService.SaveAndPublishWithStatus(test);
```

I'm not sure what the "name" field of the Nested Content JSON is for, but it doesn't seem to matter...

Thanks for the help. I use Nested Content in all of my projects!

**Comment by leekelleher** [comment]
@HarveyWilliams Cool, happy to hear that it worked out!

The "Name" field is used for an NC item's label and to populate the `IPublishedContent` Name property for front-end rendering.
