### ISSUE TITLE
AppVeyor support/integration

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-nested-content#6]
Add support for AppVeyor CI builds.

**Comment by Jeavon** [comment]
You can assign this one to me too :)

**Comment by leekelleher** [comment]
Woo! :dancer:

Thanks @Jeavon, seriously, thanks man!

**Comment by Jeavon** [comment]
No problem :blush:

**Comment by leekelleher** [comment]
Closing this issue, as @Jeavon delivered in PR #9 - I think we'll be having a few :beers: at CG15! ;-)
