### ISSUE TITLE
Always returns True to IsPropertyDirty

### ISSUE THREAD

**Issue by gordonsaxby** [leekelleher/umbraco-nested-content#61]
I am trying to detect if any of the content has changed but it always responds "true" when I check using .IsPropertyDirty, even when none of the data within the nested content control has changed.

**Comment by leekelleher** [comment]
@gordonsaxby Apologies for taking so long to respond on this.

Can you provide any more details around this?
(_So that I've got something more concrete to make a test case/scenario._)

Do you mean on the client JS or server-side C#?

**Comment by mattbrailsford** [comment]
No reply in 6 months so closing down
