### ISSUE TITLE
How do I get the "Parent" ? 

### ISSUE THREAD

**Issue by Myster** [leekelleher/umbraco-nested-content#65]
Perhaps parent is not the correct term.
But I'd like to get a handle on the node in the tree where the content is edited.
I'm only nesting one level deep so that simplifies things.

I see this discussed in #7 and #8 and it looks like I should be able to find the value I want in the `.Parent` property as of version 0.2.0, But that gives null.

Here's how I get my nested content:

```
public static IEnumerable<IPublishedContent> GetPropertyAsContentCollection(this IPublishedContent node, string alias)
{
    var value = node.GetPropertyValue<IEnumerable<IPublishedContent>>(alias, null);
    return value ?? Enumerable.Empty<IPublishedContent>();
}
```

**Comment by leekelleher** [comment]
@Myster As far as I recall, we did explore populating the `Parent` property, (as per [@mattbrailsford's closing comment](https://github.com/leekelleher/umbraco-nested-content/pull/8#issuecomment-115281454) on PR #8).  The trouble is knowing the context of nested Nested Content values.

Currently if you want to get the node of the current page, our advice is use `@Umbraco.AssignedContentItem`.

Unless you have any other ideas on potential solutions?

**Comment by benbracedigital** [comment]
If I used @Umbraco.AssignedContentItem I get the nested content IPublishedContent rather than the current page....

**Comment by leekelleher** [comment]
Hmmm, `AssignedContentItem` should be the containing (current) page - I'm not sure if something internal changed in recent Umbraco core?  An alternative would be to use `UmbracoContext.Current.PageId` and get the node from the content cache.

``` csharp
var currentPage = UmbracoContext.Current.ContentCache.GetById(UmbracoContext.Current.PageId.Value);
```

**Comment by benbracedigital** [comment]
Thank you for quick reply! Thats done it. Thank you

**Comment by glombek** [comment]
For anyone struggling with this, when using the same view for the back-end preview as on the front end, I found the following to work well:
```var parent = (Model.Parent ?? UmbracoContext.Current.PublishedContentRequest.PublishedContent);```

`Model.Parent` is populated in the backend, while we have to grab the context's property in the front end (or use `UmbracoContext.Current.PageId.Value`).

`AssignedContentItem` is returning the nested content item for me too.

**Comment by sniffdk** [comment]
Or you can get the UmbracoContext through the UmbracoHelper already available in the view:
`Umbraco.UmbracoContext.PublishedContentRequest.PublishedContent`
