### ISSUE TITLE
.GetPropertyValue generic not working right after installing NC

### ISSUE THREAD

**Issue by organicglenn** [leekelleher/umbraco-nested-content#66]
Could your PropertyValueConverter be causing this problem?

To get an image from a Media Picker I use:
`IPublishedContent image = Umbraco.TypedMedia(Model.Content.GetPropertyValue<int>("image"));`

However, after installing NC v0.2 the inner statement:
`Model.Content.GetPropertyValue<int>("image")`
returns 0 and I must use:
`IPublishedContent image = Model.Content.GetPropertyValue<IPublishedContent>("image");`
or
`Model.Content.GetPropertyValue("image")`

I'm using Umb version 7.4.3 and I believe the native PropertyValueConverters were already installed by default and the change in behavior was not until I installed NC.

**Comment by leekelleher** [comment]
Hi @organicglenn - NC's PropertyValueConverter will only run when an NC is value is being retrieved, so it's high unlikely that it's NC in this case.

When you say "native PropertyValueConverters", do you mean this project: [Umbraco Core Property Value Converters](https://our.umbraco.org/projects/developer-tools/umbraco-core-property-value-converters/)?  If so, IMO that's what has caused the change for you.

**Comment by organicglenn** [comment]
OK, yeah, that makes more sense, and I did suspect that, but I thought the Core Converters were installed initially and that I saw my reported behavior change only after I installed NC.  Maybe I'm mistaken.  Thanks!
