### ISSUE TITLE
NuGet package does not work with doctypes using compositions

### ISSUE THREAD

**Issue by MMasey** [leekelleher/umbraco-nested-content#68]
I have an Umbraco project in which i have installed NestedContent via NuGet.

When using a doctype that has been created using a composition, the composition values are not saved on publish. After looking through your closed issues i noticed that this has been fixed in the repo, but it appears that NuGet version does not include the change. I pulled down the repo and did a manual build, then switched out the dll and that solved the problem.

I'm not sure if you're waiting for your 0.3.0 release to amend this. If so, shall i create a PR to update the Known Issues part of your doc to include the problem, and temporary solution?

Cheers, and keep up the awesome work.

**Comment by leekelleher** [comment]
@MMasey Thanks for raising this. We don't currently have a release date for v0.3.0, but in the meantime we do offer a NuGet feed (on MyGet) for the latest development versions.

https://www.myget.org/feed/umbraco-packages/package/nuget/Our.Umbraco.NestedContent
