### ISSUE TITLE
Archiving the project

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-nested-content#69]
Once Umbraco releases with a native Nested Content, (currently scheduled for Umbraco v7.6.0), we will start to archive this project.

The source-code will still be available on GitHub, but there will be no new major/minor package releases.  We will support the current package release with bug-fix patches (including community pull-requests).

For future feature-requests, these would need to be made on the Umbraco issue tracker for the Umbraco Core team to review.

---

This is an open issue, if you have a different viewpoint, we're happy to discuss further.

**Comment by skttl** [comment]
So what are your takes on features right now? Is it time wasted adding new features? I have a few :)

**Comment by leekelleher** [comment]
@skttl Currently NC is in limbo mode with the migration to Umbraco core. Any new features would also need to be mirrored in the Umbraco version (and require approval from the Core team).  So for @mattbrailsford & I that might mean we have to double our efforts, (which I'd rather not).

That said, **please do share your ideas for new features**, we're definitely not closed-minds on any discussion.

**Comment by rekosko** [comment]
Given that I would like to use your Nested Content right now in my project is it better for me if I wait for 7.6 release or there won't be any major problems with migrating to Umbraco Core Nested Content? Just wondering if it will be somehow compatible so I won't get any problems when switching from one to another.

**Comment by mattbrailsford** [comment]
It' unlikely that the core NC will be compatible with the current NC implementation so if you do start with the current version, you will have to remain on the package version. In terms of waiting though, we personally haven't had chance to look at the code beyond what we did at CG16 retreat so it either hasn't moved on, or it has moved on without us so I'm not 100% sure on when it will actually be released, so if you are starting any time soon, my suggestion would be to use the current NC. When the new version comes out, you can continue to use the standalone NC, but you won't be able to switch to the new one and take advantage of any new features.

**Comment by leekelleher** [comment]
Now that NC will be part of Umbraco v7.7.0, we will do a final v0.5.0 release of the standalone package, see PR #139 for details.

After that, any future issues/feature-requests would need to be made on the Umbraco issue tracker for the Umbraco Core team to review.

Closing this ticket.
