### ISSUE TITLE
Unique Id for DetachedPublishedContent

### ISSUE THREAD

**Issue by Hendy** [leekelleher/umbraco-nested-content#7]
Being able to identify the host (top / real) IPublishedContent and the index (which could be a tree!) would be really helpful

**Comment by mattbrailsford** [comment]
We should be able to do this by populating the nodes Parent / ParentId fields, and the SortOrder property. These are currently set to default values.

Would that suffice?

**Comment by Hendy** [comment]
that'd be ideal for my circumstances :+1:  but if someone were to use a NC within an NC then the SortOrder int wouldn't be able to represent it's true index - guess that's a real edge case tho

**Comment by mattbrailsford** [comment]
that's more an issue of Level, which we should still be able to handle by settings the Level field based on it's parent's value (+1). It wouldn't be a true level in sense of true nodes, but it should suffice in being able to see it's location, relative to it's parent.

Funny this should come up here, as the same discussion is happening on the DTGE issue tracker :)

**Comment by Hendy** [comment]
ooh, yes, re-purpose Level to indicate the current level in Umbraco + levels of NC inception (also if DetachedPublishedContent wasn't internal, it'd be easy to test if an obj was of this specific type)

**Comment by Hendy** [comment]
would you like a PR for this ?

**Comment by mattbrailsford** [comment]
It you fancy giving it a go, by all means :)

**Comment by leekelleher** [comment]
Closing this issue, discussion an continue on PR #8
