### ISSUE TITLE
Radio button list doesn't work

### ISSUE THREAD

**Issue by skttl** [leekelleher/umbraco-nested-content#72]
When using radio buttons in NC, they get the same name attribute across the different items. This means, that clicking a radio button in one item, removes any settings in other items.

This is because of the way Umbraco renders a radio button list. Don't know if we can do anything about it in Nested Content.

Btw, thanks for a great plugin!

**Comment by leekelleher** [comment]
@skttl Thanks for raising this. We'll take a look to explore options (or flag it as a known issue).

**Comment by leekelleher** [comment]
Finally had chance to look at this, yup - all the radio-button-lists get given the same name attribute :-(
I'm not sure what we can do about it (within NC) at the moment.  I'll leave this issue open for now and flag it as a known issue.

**Comment by leekelleher** [comment]
Closing this one off, as it's beyond the control of Nested Content. Flagged as a known issue.
