### ISSUE TITLE
Value not saved for composition properties

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-nested-content#73]
It seems that properties inherited from compositions are not saved.
I a few document types to build to add some extra custom field in a form.

![image](https://cloud.githubusercontent.com/assets/2919859/16614765/507ccce0-4373-11e6-871a-cdd2a4efaef9.png)

And then using these in Nested Content:
![image](https://cloud.githubusercontent.com/assets/2919859/16614800/7aabf3f6-4373-11e6-91cc-6e5d9e1a7f9e.png)

But if I save these values:
![image](https://cloud.githubusercontent.com/assets/2919859/16614836/a6ad225e-4373-11e6-86c0-bb3214814de3.png)

then after reloading the page the value in Name property (inherited from composition) are gone:
![image](https://cloud.githubusercontent.com/assets/2919859/16614871/dbf354c4-4373-11e6-8788-8afe2505bab5.png)

Using Nested Content v. 0.2.0 installed via NuGet.

**Comment by bjarnef** [comment]
Just tried to remove the inherited composition property "Name" from the document type and adding it directly to itself, then it works.

**Comment by leekelleher** [comment]
@bjarnef Thanks for reporting this. The compositions bug has already been fixed in #33

We haven't released a new version of NC yet, but the dev-build is available from here:
https://ci.appveyor.com/project/leekelleher/umbraco-nested-content/build/artifacts

**Comment by bjarnef** [comment]
Okay, thanks for letting me know @leekelleher 
Any planned release date for NC v.0.3.0?

**Comment by leekelleher** [comment]
@bjarnef The v0.3.0 release has been on my to-do list for a looooong time. I actually did start to prepare for it last Friday, so it's nearly ready, just need some free time to write up release notes, etc.
