### ISSUE TITLE
Use contenttype.resource to fetch doc types

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-nested-content#78]
Nested Conent use its own API controller for fetching the available document types.
https://github.com/leekelleher/umbraco-nested-content/blob/develop/src/Our.Umbraco.NestedContent/Web/Controllers/NestedContentApiController.cs

but actually contenttype.resource already contains a method to get the content types.
https://github.com/umbraco/Umbraco-CMS/blob/75c2b07ad3a093b5b65b6ebd45697687c062f62a/src/Umbraco.Web.UI.Client/src/common/resources/contenttype.resource.js#L149

it seems this method was added as a part of Umbraco 7.4 
https://github.com/umbraco/Umbraco-CMS/commit/d62ae17f050d4232d9f154f3f520b1039fbf2d00

Maybe use this method in 7.4+ by checking the server version variable and fallback to the method in ApiController?
For a future release, where Nested Content maybe shouldn't support older version, this part can be removed. It might also be useful if using some of the new directives/components which is a part of 7.4+, e.g. whether to use umb-overlay or dialogService.

**Comment by mattbrailsford** [comment]
Thanks Bjarne,

Nested Content is actually in the process of being implemented in Umbraco Core, so really, once that is complete, this package will essentially become a maintenance project with the one in core becoming the one for future releases. With that in mind, it's unlikely we will look at this as part of this package as these things will get addressed when it is merged in to core.

Matt

**Comment by bjarnef** [comment]
Ahh okay, it makes sense to stick with the ApiController in this project then.

For your other package Photon, you can use same approach to fetch document types (instead of entering an alias).

Let´s disquess it in the issue over here: https://github.com/mattbrailsford/umbraco-photon/issues/2
