### ISSUE TITLE
Issue installing Nested content on new copy of Umbraco

### ISSUE THREAD

**Issue by vickieallen** [leekelleher/umbraco-nested-content#80]
![image](https://cloud.githubusercontent.com/assets/5023006/17246473/3217beae-5584-11e6-8261-1c59064d1f50.png)

I have a fresh copy of Umbraco and am receiving this error when installing Nested Content. I have done it in the past with no issues. 

Is there an issue?

**Comment by mattbrailsford** [comment]
Looks like a core issue with the package repository rather than a NC issue.
I'd suggest downloading it manually from our.umbraco.org and install it via
the package installer instead.

**Comment by vickieallen** [comment]
Yay that worked! Thanks!

**Comment by mattbrailsford** [comment]
Awesome! Glad it worked.
