### ISSUE TITLE
Multiple tabs from the same doctype

### ISSUE THREAD

**Issue by tompipe** [leekelleher/umbraco-nested-content#81]
When adding a doctype to use as a blueprint, you can select doctype1/tab1. You can then add a 2nd blueprint and select doctype1/tab2.

This causes doctype1 to show twice in the popup when adding content items, and clicking either icon adds the same fields (e.g tab1)
- Should you be prevented from selecting multiple tabs off the same doctype? 
- Should multiple tabs be merged when adding content?
- Or should different tabs be treated as different blueprints, but the labels differ when adding content? 

Thoughts?

**Comment by mattbrailsford** [comment]
Good find :)

Each doc type + tab config should be a distinct option in the dialog,
however that seems to be failing (bug). But I guess there is a second issue
of even.if this worked, how do you differentiate the two?

Given NC is moving into core, and at the same time a new "scheme type" is
coming that is similar to a doc type but with no tabs, which the core NC
will use, this will naturally get fixed, but for this instance, I'm tempted
to say we won't bother fixing it and just suggest to use separate doc
types.

Sound fair?

As I say, nice find though :)

**Comment by mkaziz** [comment]
I'm using this in Umbraco Core and seeing the same issue.

**Comment by leekelleher** [comment]
Hi @mkaziz - the best bet is to check the Umbraco issue tracker to see if a ticket for this issue already exists, if not, please feel free to raise a new ticket: <http://issues.umbraco.org/issues/U4?q=Nested%20Content#newissue=yes>
