### ISSUE TITLE
Choose Type Of Content modal dialog layout

### ISSUE THREAD

**Issue by billbixby** [leekelleher/umbraco-nested-content#84]
The 'CHOOSE TYPE OF CONTENT' modal when adding a new row to a nested content block currently displays as a grid of icons with limited space for the name of the items. DocType names that go over two lines have the bottom of the text cropped too. 

It would be  more useable to change the view to have a list layout instead of the grid, where available types are given more space and we can use more descriptive names to help our content editors.

**Comment by mattbrailsford** [comment]
We do this for consistency with how umbraco do this for the grid. This is likely an issue they have also so we will wait to see how they resolve it as I'd like to keep it consistent. Closing for now.
