### ISSUE TITLE
Value within last item not saved unless you collapse the field.

### ISSUE THREAD

**Issue by Will-i-am-** [leekelleher/umbraco-nested-content#88]
Hi guys, got a little bit of a problem with a Nested Content within a Vorto. Had a quick look and couldn't see any issue that was similar.

Umbraco 7.4.3
Nested Content 0.3.0
Vorto (originally v1.2.0.0 with modifications)

The issue is, is when you create a new block of content, (say for example its just a simple text string) and you entered in some text and hit save, that value would not be saved, but if you enter in some text, hit the edit button (or force that block to collapse) then it will save the value.

**Comment by leekelleher** [comment]
@Will-i-am- Thanks for reporting this. Can you reproduce the issue without Vorto? (It reduces complications for us)

**Comment by Will-i-am-** [comment]
Thanks Lee, Will be sure to check this for you ASAP

**Comment by mattbrailsford** [comment]
Unable to replicate, or possibly fixed in other commit.

Setup vorto as described and value was saved successfully. Closing till further information provided.
