### ISSUE TITLE
Value from MNTP not saved

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-nested-content#93]
I have the following entries in Nested Content v. 0.2.0 and Umbraco v. 7.4.1

![image](https://cloud.githubusercontent.com/assets/2919859/19620323/77d2e858-987b-11e6-911e-8aae9448ea6f.png)

It has a language dropdown to using nuPickers DotNet datasource, a multiline text, a button text and a MNTP to select a site node.

However is first entry (da-DK), when selecting a node in MNTP - after save the selected node in first entry is gone - actually is doesn't seem to save this one.

![image](https://cloud.githubusercontent.com/assets/2919859/19620356/2cb4ae64-987c-11e6-8c1f-b7e9915b0924.png)

After save I have the following in umbraco.config

```
<priceLanguageConfig><![CDATA[[{"name":"da-DK","ncContentTypeAlias":"languagePriceConfig","language":"da-DK","text":"Some text for danish...","buttonText":"Go to site","buttonLink":"http://hojmark.dk"},{"name":"sv-SE","ncContentTypeAlias":"languagePriceConfig","language":"sv-SE","text":"Some text for swedish...","buttonText":"Go to site","buttonLink":"2454"},{"name":"nb-NO","ncContentTypeAlias":"languagePriceConfig","language":"nb-NO","text":"Some text for norwegian...","buttonText":"Go to site","buttonLink":"2454"}]]]></priceLanguageConfig>
```

**Comment by bjarnef** [comment]
Okay, the link for actually previously a textstring property, where da-DK had a value "http://hojmark.dk".
But after changing property to MNTP it returned a console error, where I think it was entityResource trying to lookup value from that string something like "Document=Content&Ids=http://hojmark.dk"

And guess that prevented it from save the new value. It is probably an issue in core and not sure if it has been fixed. It should really parse the ids before looking up the value, so you don't get an issue like this when changing from e.g. a textstring to a MNTP.

Anyway I just deleted the values and re-created them - after this the selected id from MNTP was stored correct.

```
<priceLanguageConfig><![CDATA[[{"name":"da-DK","ncContentTypeAlias":"languagePriceConfig","language":"da-DK","text":"Some text for danish...","buttonText":"Go to site","buttonLink":"2454"},{"name":"sv-SE","ncContentTypeAlias":"languagePriceConfig","language":"sv-SE","text":"Some text for swedish...","buttonText":"Go to site","buttonLink":"2454"},{"name":"nb-NO","ncContentTypeAlias":"languagePriceConfig","language":"nb-NO","text":"Some text for norwegian...","buttonText":"Go to site","buttonLink":"2454"}]]]></priceLanguageConfig>
```

**Comment by leekelleher** [comment]
@bjarnef Just checking, is this okay to close off?

**Comment by bjarnef** [comment]
@leekelleher yes, I just think it is an issue in Umbraco - maybe it has been fixed.

E.g. if you add some text in a textstring property and save. Next change the datatype of the property to MNTP. Then I think it try looking up the existing text, but return an console error, because it is not an id.

**Comment by leekelleher** [comment]
Ah ok, yeah - makes sense, still sucks.  I think the same would happen on a regular property too.
