### ISSUE TITLE
Include all tabs of a doctype

### ISSUE THREAD

**Issue by JoseMarcenaro** [leekelleher/umbraco-nested-content#94]
This is related to #81, but not exactly the same.

Would it be possible (and wise) to implement the option of including all tabs of a selected doc type, instead of choosing one?  Something like adding an **\- all -** option to the tab selection dropdown.

The reason why I ask this is because in some cases, the same Doc Type can be used in the DTGE (i.e. to provide a "data block" to be rendered with a custom view) and as a Nested Content type.

The DTGE does a very nice work putting all the tabs together, and I wonder if it would make sense to have something similar (with or without the tab titles) in Nested Content.

**Comment by mattbrailsford** [comment]
In all honesty, although we built DTGE, I'm not that happy that we chose to show all tabs in it as IMO IT makeS it overly cluttered. NC is meant for simple lists and including all tabs in such a small area just adds a load of clutter we wanted to avoid so it's not something we plan to add.

My suggestion would be to put all your properties on one tab then you can use it for both NC and DTGE.
