### ISSUE TITLE
Feature Request: Duplicate Item

### ISSUE THREAD

**Issue by ProNotion** [leekelleher/umbraco-nested-content#98]
It would be great to be able to clone/duplicate an item that has already been created in a Nested Content property. For instance, if you have a list of items to put together where many of the items share similar property values e.g. an apartment in an apartment block it would be a great time saver to duplicate a previously added item and amend only the properties that have a different property value.

**Comment by leekelleher** [comment]
Closing this request, as we don't want to introduce any features that are different to the version we migrated to (upcoming) Umbraco v7.7.0.

If you still want this feature in a future Umbraco release, please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
