### ISSUE TITLE
Feature Request: ability to drag NC Item between other NC properties

### ISSUE THREAD

**Issue by madsoulswe** [leekelleher/umbraco-nested-content#99]
- Ability to drag item between node properties.
- Ability to drag item between properties inside item and to parent/child.

Thus be able to drag items allover the place between other nested content properties. :+1: :muscle:

**Comment by mattbrailsford** [comment]
Personally, I think the complexity this will add to the codebase will far outweigh the potential gain for what I believe to be a bit of an edge case feature. Sure, drag and drop is nice, but I've never seen it implemented 100% successfully and usually involves fixing edge case bugs when it doesn't quite work right. I'd much rather keep it simple and focus dev time on more beneficial features.

**Comment by leekelleher** [comment]
Closing this request, as we don't want to introduce any features that are different to the version we migrated to (upcoming) Umbraco v7.7.0.

If you still want this feature in a future Umbraco release, please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
